### ISSUE TITLE
jnxlibc does not install on Elementary system with default version of CMake

### ISSUE THREAD

**Issue by draganglumac** [AlexsJones/jnxlibc#59]
By default, Elementary seems to be hosting cmake 2.8.7 in their repos. But despite CMakeLists.txt suggesting that minimum CMake version is 2.8 the cmake call fails with the following error:

-- Configuring done
CMake Error at CMakeLists.txt:30 (add_library):
  Cannot find source file:

    $<TARGET_OBJECTS:jnxlibc_core>

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error in CMakeLists.txt:
  Cannot find source file:

    OBJECT

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

**Comment by AlexsJones** [comment]
If this is blocking you I could add shared object/static lib and send it over

**Comment by draganglumac** [comment]
Not a blocker and I believe I've fixed it. Sending the pull request.
