### ISSUE TITLE
Intermittant TCP success 

### ISSUE THREAD

**Issue by AlexsJones** [AlexsJones/jnxlibc#70]
http://showterm.io/6dec88186b68bec399bb2

https://www.dropbox.com/s/z7yznise7o80w2t/library_fixing.tar.gz?dl=0

**Comment by AlexsJones** [comment]
I think this is due to the time delay threading out the listener callback. 
Still investigating it in whisper

**Comment by AlexsJones** [comment]
Adding a sleep after the tcp_send() seems to have fixed the problem in whisper

**Comment by draganglumac** [comment]
Hmmm... Yeah I am a bit worried about having to add that delay... I'll investigate today will get more info from you on Skype
