### ISSUE TITLE
Library needs to be migrated to /usr/local because El Capitan blocks sudo access to /usr

### ISSUE THREAD

**Issue by draganglumac** [AlexsJones/jnxlibc#99]
Just hit the snag that you seemed to have hit late last year that you can't install jnxlibc on El Capitan (OS X 10.11) Reason being new security measures as this article suggests http://www.macworld.com/article/2948140/os-x/private-i-el-capitans-system-integrity-protection-will-shift-utilities-functions.html

El Capitan blocks write access even to users with admin privileges to /sbin /usr /bin, but it leaves /usr/local accessible.

What do you think about deploying jnxlibc there instead?

**Comment by AlexsJones** [comment]
that's not a problem, infact I think you can do something like 

`cmake . -DINSTALL_DIR=/usr/local`
are you suggesting to make it the default?

**Comment by draganglumac** [comment]
Ah I didn't realise we could. In that case we should probably update the README to suggest it as a solution for El Capitan :)

I don't mind doing that if you want

**Comment by draganglumac** [comment]
Hm... didn't work for me :( I tried passing -DINSTALL_DIR=/usr/local and it told me that it won't have any effect.

When I passed in -DINSTALL_PREFIX=/usr/local it didn't complain but it had no effect on the install path.

Boo :( Google is not terribly helpful about it.

**Comment by AlexsJones** [comment]
I'm suprised as https://github.com/AlexsJones/jnxlibc/blob/master/CMakeLists.txt#L90 shows where the change is used

**Comment by draganglumac** [comment]
I found something, seems to need CACHE qualifier like so

... set(INSTALL_PREFIX /usr CACHE PATH "installation root directory") ...

and then on the command line you pass

cmake . -DINSTALL_PREFIX:PATH=/usr/local

Tested it, it works OK. I'll see if there's a simpler way.

**Comment by AlexsJones** [comment]
Oh it probably wasn't overriding the local data cache, so you've moved it there.
In future anytime you change the cmake. commands e.g. `cmake . -DRUN_TESTS=OFF` you have to go `git clean -xf` to remove the `CMakeCache` files at least that's my experience

**Comment by draganglumac** [comment]
No no, definitely cleaned it between successive runs every time. I think it was a bug :( Anyways the PR I submitted tested to work, and I've updated README as well so you can cast your eye over it to see the small changes I've made and if you're OK with them merge the PR.
